#!/bin/bash
export LANG=en_US.UTF-8
action=${1:-start}

case $action in
    start)
        cd /sitebot && pybabel compile -d translations
        # 统一挂载ssh 目录到/var/sitebot
        if [ ! -d "/var/sitebot/ssh" ];then mkdir -p /var/sitebot/ssh; fi        
        ln -s /var/sitebot/ssh /root/.ssh
        python /sitebot.py
        ;;
    shell)
        exec /bin/bash
        ;;
    python)
        exec python
        ;;
    *)
        echo "Available CMD: start | python | shell"
        ;;
esac
