#!/bin/bash
export LANG=en_US.UTF-8
action=${1:-start}

case $action in
    start)
        cd /sitebot && pybabel compile -d translations
        python /sitebot.py
        ;;
    shell)
        exec /bin/bash
        ;;
    python)
        exec python
        ;;
    *)
        echo "Available CMD: start | python | shell"
        ;;
esac
